# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'unify' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for unify
  
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'

end
